version: "3.7"

services:
  api:
    image: kamailio-api/php
    container_name: slim_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      - docker="true"
      - LOCALHOST_MACHINE_IP=${LOCALHOST_MACHINE_IP}
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_PROCESS_TIMEOUT=1200
    ports:
      - ${WEB_EXPOSE_PORT}:8080
    volumes:
      - .:/var/www
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini:ro
  db:
    image: mysql:5.7
    container_name: slim_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ./docker/mysql/slim:/var/lib/mysql:rw
      - ./docker/config/mysql:/etc/mysql/conf.d:ro