version: "3.7"

services:
  api:
    image: kamailio-api/php
    container_name: slim_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      docker: "true"
    ports:
      - 8080:8080
    volumes:
      - .:/var/www