version: "3.7"

services:
  api:
    image: kamailio-api/php
    container_name: slim_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    working_dir: /var/www
    command: php -S 0.0.0.0:8080 -t public
    environment:
      - docker="true"
      - LOCALHOST_MACHINE_IP=${LOCALHOST_MACHINE_IP}
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_PROCESS_TIMEOUT=1200
    ports:
      - ${WEB_EXPOSE_PORT}:8080
    volumes:
      - .:/var/www
      - ./docker/config/php/php.ini:/usr/local/etc/php/php.ini:ro
  